name: Run Tests and Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv flask openai pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      
      - name: Run Pylint
        run: |
          cd Tutor && pylint *.py --exit-zero
      
      - name: Run Tests with Environment Setup
        run: |
          # Create a mock .env file for testing
          echo "OPENAI_API_KEY=dummy_key_for_testing" > .env
          python -m pytest tests/ -v
